#========================= For LOCAL DEV SCHEMA
energy_local = '''
  CREATE TABLE IF NOT EXISTS public.energy (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    units VARCHAR(20) NOT NULL,
    price DECIMAL(20,2) NOT NULL,
    change VARCHAR(20),
    percent_change VARCHAR(20),
    contract VARCHAR(20),
    time_edt VARCHAR(20),
    submission_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT energy_pkey PRIMARY KEY (id)
);
'''

agriculture_local = '''
  CREATE TABLE IF NOT EXISTS public.agriculture (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    units VARCHAR(20) NOT NULL,
    price DECIMAL(20,2) NOT NULL,
    change VARCHAR(20),
    percent_change VARCHAR(20),
    contract VARCHAR(20),
    time_edt VARCHAR(20),
    submission_date DATE NOT NULL DEFAULT CURRENT_DATE,
     CONSTRAINT agriculture_pkey PRIMARY KEY (id)
);
'''

metal_local = '''
  CREATE TABLE IF NOT EXISTS public.metal (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    units VARCHAR(20) NOT NULL,
    price DECIMAL(20,2) NOT NULL,
    change VARCHAR(20),
    percent_change VARCHAR(20),
    contract VARCHAR(20),
    time_edt VARCHAR(20),
    submission_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT metal_pkey PRIMARY KEY (id)
);
'''
commodities_local = '''
  CREATE TABLE IF NOT EXISTS public.Commodities (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    value DECIMAL(20,2) NOT NULL,
    change VARCHAR(20) NOT NULL,
    percent_change VARCHAR(20),
    high DECIMAL(20,2),
    low DECIMAL(20,2),
    time_edt VARCHAR(20),
    submission_date DATE NOT NULL DEFAULT CURRENT_DATE,
     CONSTRAINT commodities_pkey PRIMARY KEY (id)
);
'''

#========================= For DEV SCHEMA
energy = '''
  CREATE TABLE dev.energy (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    units VARCHAR(20) NOT NULL,
    price DECIMAL(20,2) NOT NULL,
    change VARCHAR(20),
    percent_change VARCHAR(20),
    contract VARCHAR(20),
    time_edt VARCHAR(20),
    submission_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT energy_pkey PRIMARY KEY (id)
);
'''

agriculture = '''
  CREATE TABLE dev.agriculture (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    units VARCHAR(20) NOT NULL,
    price DECIMAL(20,2) NOT NULL,
    change VARCHAR(20),
    percent_change VARCHAR(20),
    contract VARCHAR(20),
    time_edt VARCHAR(20),
    submission_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT agriculture_pkey PRIMARY KEY (id)
);
'''

metal = '''
  CREATE TABLE dev.metal (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    units VARCHAR(20) NOT NULL,
    price DECIMAL(20,2) NOT NULL,
    change VARCHAR(20),
    percent_change VARCHAR(20),
    contract VARCHAR(20),
    time_edt VARCHAR(20),
    submission_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT metal_pkey PRIMARY KEY (id)
);
'''
commodities = '''
  CREATE TABLE dev.Commodities (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    value DECIMAL(20,2) NOT NULL,
    change VARCHAR(20) NOT NULL,
    percent_change VARCHAR(20),
    high DECIMAL(20,2),
    low DECIMAL(20,2),
    time_edt VARCHAR(20),
    submission_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT commodities_pkey PRIMARY KEY (id)
);
'''

# =============================================== FOR STAR SCHEMA
fact_market_data = '''
CREATE TABLE IF NOT EXISTS prod.ft_historical_data (
        id INT GENERATED BY DEFAULT AS IDENTITY
        ,symbol_id INT
        ,units VARCHAR(20) NOT NULL
        ,price DECIMAL(20,2) NOT NULL
        ,value DECIMAL(20,2) NOT NULL
        ,change VARCHAR(20) NOT NULL
        ,percent_change VARCHAR(20)
        ,contract VARCHAR(20)
        ,high DECIMAL(20,2)
        ,low DECIMAL(20,2)
        ,time_edt VARCHAR(20)
        ,submission_date DATE NOT NULL DEFAULT CURRENT_DATE
        ,CONSTRAINT fact_market_data_pkey PRIMARY KEY (id)
    );
'''

dim_categories = '''
     CREATE TABLE IF NOT EXISTS prod.dim_types (
        id INT GENERATED BY DEFAULT AS IDENTITY
        , name VARCHAR(50)
        ,CONSTRAINT dim_categories_pkey PRIMARY KEY (id)
    );
''' 

dim_symbols = '''
     CREATE TABLE IF NOT EXISTS prod.dim_symbols (
        id INT GENERATED BY DEFAULT AS IDENTITY,
        cat_id INT,
        ,name VARCHAR(50)
        ,CONSTRAINT dim_Symbol_pkey PRIMARY KEY (id)
    );
''' 

dim_dates = '''
    CREATE TABLE IF NOT EXISTS prod.dim_types (
        id INT GENERATED BY DEFAULT AS IDENTITY
        , date DATE
        , year INT
        , month INT
        , day INT
        , quarter VARCHAR
        , is_weekend BOOLEAN
    );
'''
local_tables =[agriculture_local,commodities_local,metal_local,energy_local]
dev_tables = [agriculture,commodities,metal,energy]
transformed_tables = [fact_market_data,dim_categories,dim_symbols,dim_dates]